language: cpp
# This section installs the necessary dependencies.
addons:
  apt:
    packages:
      - cmake-data
      - cmake
      - lcov

# Define the matrix explicitly, manually expanding the combinations of (os, compiler, env).
# It is more tedious, but grants us far more flexibility.
matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      env: BUILD_TYPE=Debug VERBOSE=1 CXX_FLAGS=-std=c++14
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Release VERBOSE=1 CXX_FLAGS=-std=c++14 -Wgnu-zero-variadic-macro-arguments
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Release VERBOSE=1 CXX_FLAGS=-std=c++14 NO_EXCEPTION=ON NO_RTTI=ON COMPILER_IS_GNUCXX=ON
    - os: osx
      compiler: gcc
      env: BUILD_TYPE=Release VERBOSE=1 CXX_FLAGS=-std=c++14 HOMEBREW_LOGS=~/homebrew-logs HOMEBREW_TEMP=~/homebrew-temp
    - os: osx
      compiler: clang
      env: BUILD_TYPE=Release VERBOSE=1 CXX_FLAGS=-std=c++14 HOMEBREW_LOGS=~/homebrew-logs HOMEBREW_TEMP=~/homebrew-temp
    - os: linux
      compile: gcc
      dist: bionic
      env: BUILD_TYPE=Debug VERBOSE=1 CXX_FLAGS=-std=c++14 BUILD_COVERAGE=ON
      after_success:
        - pip install --user cpp-coveralls
        - cd build
        - coveralls -r .. --gcov-options '\-lp' -E '.*_unittest.cc$' -e gtest -e build/CMakeFiles

dist: xenial 

script: ./ci/travis.sh
